[package]
name = "winctl-tray"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
toml.workspace = true
uuid.workspace = true
winctl = { path = "../winctl" }

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[target.'cfg(all(windows, target_env = "msvc"))'.dependencies]
winit.workspace = true
wry.workspace = true
